FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
RUN adduser --disabled-password --gecos "" --uid 10001 appuser
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["1-Presentation/MotorcycleRAG.API/MotorcycleRAG.API.csproj", "1-Presentation/MotorcycleRAG.API/"]
COPY ["2-Application/MotorcycleRAG.Application/MotorcycleRAG.Application.csproj", "2-Application/MotorcycleRAG.Application/"]
COPY ["3-Domain/MotorcycleRAG.Domain/MotorcycleRAG.Domain.csproj", "3-Domain/MotorcycleRAG.Domain/"]
COPY ["3-Domain/MotorcycleRAG.Contracts/MotorcycleRAG.Contracts.csproj", "3-Domain/MotorcycleRAG.Contracts/"]
COPY ["3-Domain/MotorcycleRAG.Contracts.Models/MotorcycleRAG.Contracts.Models.csproj", "3-Domain/MotorcycleRAG.Contracts.Models/"]
COPY ["4-Persistence/MotorcycleRAG.Persistence/MotorcycleRAG.Persistence.csproj", "4-Persistence/MotorcycleRAG.Persistence/"]
COPY ["0-Base/MotorcycleRAG.Core/MotorcycleRAG.Core.csproj", "0-Base/MotorcycleRAG.Core/"]

RUN dotnet restore "1-Presentation/MotorcycleRAG.API/MotorcycleRAG.API.csproj"

COPY . .
RUN dotnet publish "1-Presentation/MotorcycleRAG.API/MotorcycleRAG.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --chown=appuser:appuser --from=build /app/publish .
USER appuser
ENTRYPOINT ["dotnet", "MotorcycleRAG.API.dll"]
