using System.Text.Json.Serialization;

namespace MotorcycleRAG.Contracts.Models.DTOs;

/// <summary>
/// Request body for POST /api/ingestion/jobs — creates a queued ingestion job for the local processor.
/// The uploadId references a previously uploaded blob; no filesystem paths are accepted.
/// </summary>
public sealed record IngestionJobStartRequest
{
    /// <summary>
    /// Opaque reference to the uploaded file (blob key or upload GUID returned by the upload endpoint).
    /// Must never be a raw filesystem path.
    /// </summary>
    public string UploadId { get; init; } = string.Empty;

    /// <summary>
    /// Type of document: "manual-pdf", "spec-dataset", or "bike-graph".
    /// </summary>
    public string DocumentType { get; init; } = string.Empty;

    /// <summary>
    /// Processor run identifier generated by Admin Desktop and echoed by stage status callbacks.
    /// </summary>
    [JsonPropertyName("processorRunId")]
    public required string ProcessorRunId { get; init; }

    /// <summary>
    /// Optional original filename of the uploaded document (e.g. "2023-honda-cbr600rr.pdf").
    /// Persisted on the job so the frontend can display it in status responses.
    /// </summary>
    public string? SourceFileName { get; init; }

    /// <summary>
    /// Optional pipeline configuration overrides.
    /// </summary>
    public IngestionJobConfiguration? Configuration { get; init; }
}
