encryptionsalt: v1:3oyzel1BB30=:v1:/i3JAz+/frrLrrfN:pHGAt0fmO+IZqTZP1BFGbKYKrd7vog==
config:
  motorcycle-rag-infra:sqlAdminLogin: sqladmin
  motorcycle-rag-infra:sqlAdminPassword:
    secure: v1:NfakokezkjFDgc7m:CTcW3YNUNmE0Ppp3ioIWRvmaOO2Z18ApVi4OsmrQ14Tz/jPXb0xSxjT8xBhqWBs1
